### ISSUE TITLE
好像不可用了。

### ISSUE THREAD

**Issue by luzikai** [Dr-TSNG/HIT-clock#14]
Run python 每日上报.py
Traceback (most recent call last):
初始化浏览器
  File "/home/runner/work/HIT-clock/HIT-clock/每日上报.py", line 20, in <module>
正在上报
    driver.find_element_by_id('load').click()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="load"]"}
  (Session info: headless chrome=93.0.4577.63)

Error: Process completed with exit code 1

**Comment by Dr-TSNG** [comment]
re-run一次试试，我没有遇到问题，说不定只是服务器卡了

**Comment by luzikai** [comment]
确实，现在可以了
