### ISSUE TITLE
请问从24号开始总是上报失败是什么原因呢

### ISSUE THREAD

**Issue by zxy-HIT** [Dr-TSNG/HIT-clock#6]
Run python 每日上报.py
Traceback (most recent call last):
初始化浏览器
  File "/home/runner/work/HIT-clock/HIT-clock/每日上报.py", line 22, in <module>
正在上报
    driver.get('https://xg.hit.edu.cn/zhxy-xgzs/xg_mobile/xs/yqxx')
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=91.0.4472.101)

Error: Process completed with exit code 1.

**Comment by Dr-TSNG** [comment]
因为学工系统变内网了，要用 vpn 访问，10分钟前我刚修完，更新 fork 就行啦

**Comment by zxy-HIT** [comment]
> 因为学工系统变内网了，要用 vpn 访问，10分钟前我刚修完，更新 fork 就行啦

谢谢老哥
