### ISSUE TITLE
最近总是build失败啊，start clock出错，学工页面的审核状态也是未提交而不是待审核

### ISSUE THREAD

**Issue by yuanziyongheng** [Dr-TSNG/HIT-clock#7]
Run python 每日上报.py
Traceback (most recent call last):
初始化浏览器
正在上报
  File "/home/runner/work/HIT-clock/HIT-clock/每日上报.py", line 28, in <module>
    driver.find_element_by_id('center').find_elements_by_tag_name('div')[5].click()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="center"]"}
  (Session info: headless chrome=91.0.4472.114)

Error: Process completed with exit code 1.

**Comment by Dr-TSNG** [comment]
似乎因为通过 vpn 访问的原因，网络不是很稳定，我试着加个 try 失败了多试几次

**Comment by yuanziyongheng** [comment]
> 似乎因为通过 vpn 访问的原因，网络不是很稳定，我试着加个 try 失败了多试几次

嗯。。。昨天稳了一次，今天就一直在报错了，错误还是老样子orz

**Comment by Dr-TSNG** [comment]
已更新，失败会重试5次，应该能满足网络不稳定时的问题了

**Comment by yuanziyongheng** [comment]
> 已更新，失败会重试5次，应该能满足网络不稳定时的问题了

感谢感谢，今天成功了
